test heml values update

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -45,11 +45,35 @@ jobs:
           IMAGE_TAG: ${{ github.sha }}
         run: docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
       
-      - name: Push Docker Image
+      # - name: Push Docker Image
+      #   env:
+      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+      #     IMAGE_TAG: ${{ github.sha }}
+      #   run: |
+      #     aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY
+      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
+      #     echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
+
+      - name: Update Helm values.yaml
         env:
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
           IMAGE_TAG: ${{ github.sha }}
         run: |
-          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY
-          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
-          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
+          current_tag=$(cat helm/node-app/values.yaml | grep image | cut -d ':' -f 2)
+          current_tag=$(cat helm/node-app/values.yaml | grep image | cut -d ':' -f 2)
+          sed -i "s/$current_tag/$IMAGE_TAG/g" helm/node-app/values.yaml
+          
+          # Check that the tag has been updated
+          if [[ $(cat helm/node-app/values.yaml | grep image | cut -d ':' -f 2) == "$IMAGE_TAG" ]]; then
+            echo "Tag updated successfully"
+          else
+            echo "Tag update failed"
+            exit 1
+          fi
+
+      - name: Push values changes to repo without actions trigger
+        run: |
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git config --global user.name "github-actions[bot]"
+          git add helm/node-app/values.yaml
+          git commit -m "Update values.yaml with new image tag"
+          git push origin main
